#!/bin/bash
git init
git add .gitignore Dockerfile LICENSE Makefile README.md circle.yml main.go
git commit -m "$(printf '{{ cookiecutter.project_name }} initial commit\n\nThis code was autogenerated using \nhttps://github.com/weaveworks-plugins/scope-plugin-generator')"

# add weaveworks build-tools
git subtree add --prefix tools/ https://github.com/weaveworks/build-tools master --squash
